Feature/global 3w UI
IFRCGo/go-frontend pull request #1933
Opened 2021-06-10 13:14 UTC by barshathakuri

Fetch data from API to 3W page

2021-06-14 08:27 UTC, AdityaKhatri requested changes

2021-06-14 08:27 UTC, AdityaKhatri commented on src/root/views/GlobalThreeW/index.tsx
> +    url: `api/v2/global-project/ns-ongoing-projects-stats/`,
```suggestion
    url: 'api/v2/global-project/ns-ongoing-projects-stats/',
```

2021-06-14 08:27 UTC, AdityaKhatri commented on src/root/views/GlobalThreeW/index.tsx
> +    url: `api/v2/global-project/overview/`,
```suggestion
    url: 'api/v2/global-project/overview/',
```

2021-06-14 08:27 UTC, AdityaKhatri commented on src/root/views/GlobalThreeW/index.tsx
> +  }, [nsProjectsResponse]);
```suggestion
  const numTotalProjects = React.useMemo(() => (
      nsProjectsResponse?.results
          .map((r: NsProjectsOverviewFields) => r.ongoing_projects)
          .reduce((acc, val) => acc + val, 0)
  ), [nsProjectsResponse]);
```

2021-06-15 03:06 UTC, frozenhelium approved these changes

2021-06-15 03:07 UTC, merged