Feature/local 3w
IFRCGo/go-frontend pull request #1935
Opened 2021-06-13 12:11 UTC by frozenhelium

2021-06-13 14:02 UTC, AdityaKhatri requested changes

2021-06-13 14:02 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true }
```suggestion
    { normal: true },
```

2021-06-13 14:02 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true }
```suggestion
    { normal: true },
```

2021-06-13 14:02 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true }
```suggestion
    { normal: true },
```

2021-06-15 01:47 UTC, frozenhelium commented on src/root/components/Card/index.tsx
> +  children?: React.ReactNode;
Children can be optional

2021-06-15 01:47 UTC, frozenhelium commented on src/root/components/KeyFigureCard/index.tsx
> +function KeyFigureCard(props: Props) {
Removed

2021-06-15 01:50 UTC, frozenhelium commented on src/root/utils/restRequest/index.ts
> +};
That's exactly why I put it in the `index.ts`

2021-06-15 01:51 UTC, merged