Feature/alert debug message
IFRCGo/go-frontend pull request #1951
Opened 2021-06-27 16:57 UTC by frozenhelium

2021-06-28 11:12 UTC, tnagorra requested changes

2021-06-28 11:12 UTC, tnagorra commented on src/root/components/Alert/index.tsx
> +            Copy detailed error
No need to translate this?

2021-06-28 11:52 UTC, AdityaKhatri requested changes

2021-06-28 11:52 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/NSProjects/SankeyFilters/index.tsx
> +        return newFilterValue;
```suggestion
      onChange((oldFilterValue) => ({
          ...oldFilterValue,
          [name]: newValue,
        })
```

2021-06-28 11:52 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true, precision: 'auto' }
```suggestion
    { normal: true, precision: 'auto' },
```

2021-06-28 11:52 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true, precision: 'auto' }
```suggestion
    { normal: true, precision: 'auto' },
```

2021-06-28 11:52 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/projectTableColumns.ts
> +    { normal: true, precision: 'auto' }
```suggestion
    { normal: true, precision: 'auto' },
```

2021-06-29 07:45 UTC, AdityaKhatri requested changes

2021-06-29 07:45 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/NSProjects/Map/index.tsx
> +            label="Reporting NS"
string left

2021-06-29 07:45 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/NSProjects/Map/index.tsx
> +            label="Receiving Country"
string left

2021-06-29 07:45 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/NSProjects/index.tsx
>      const ongoingBudget = ongoing.reduce((acc, val) => acc + (+(val.budget_amount ?? 0)), 0);
I think we created a sum function. Could you use it here?

2021-06-29 07:45 UTC, AdityaKhatri commented on src/root/views/Country/ThreeW/NSProjects/index.tsx
> +    const target = filteredProjectList.reduce((acc, val) => acc + (+(val.target_total ?? 0)), 0);
I think we created a sum function. Could you use it here?

2021-06-29 07:47 UTC, tnagorra commented on src/root/views/Country/ThreeW/NSProjects/index.tsx
> +    const target = filteredProjectList.reduce((acc, val) => acc + (+(val.target_total ?? 0)), 0);
Let's use sum function please

2021-06-29 10:18 UTC, AdityaKhatri approved these changes

2021-06-29 10:19 UTC, merged