Informal Update
IFRCGo/go-frontend pull request #2189
Opened 2022-01-18 11:25 UTC by frozenhelium

2022-02-07 09:42 UTC, barshathakuri commented on src/root/views/InformalUpdateReport/index.tsx
> +import { IoShareSocialOutline } from 'react-icons/io5';
Please move absolute imports before relative.

2022-02-12 04:34 UTC, AdityaKhatri requested changes

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +    response: reportResponse
```suggestion
    response: reportResponse,
```

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +    { link: '/', name: strings.breadCrumbHome }
break into multiple lines with each line having only one item

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +    { link: '/', name: strings.breadCrumbHome }
Also, end the object with ,

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +              {reportResponse?.country_district?.map((item) => (item?.country_details?.name)).join('-')}
Do this outside in a memo

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +            icons={<IoShareSocialOutline />}
What does this button do? If the work is still left, add a TODO

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +                      </div>
use ListView if possible, this is a big chunk and would be more readable if done in a separate component

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
>    };
Move this outside in a separate component

2022-02-12 04:34 UTC, AdityaKhatri commented on src/root/views/InformalUpdateReport/index.tsx
> +              <Container heading={strings.informalUpdateActionTakenLabel} className={styles.actionTaken}>
drop in multiple lines

2022-02-18 10:08 UTC, merged