Feature/preparedness validation
IFRCGo/go-frontend pull request #2421
Opened 2022-07-21 09:54 UTC by barshathakuri

2022-07-29 10:03 UTC, AdityaKhatri requested changes

2022-07-29 10:03 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/useEapFormOptions.ts
> +  });
@frozenhelium , can we somehow call this separately so that we don't call it in each form?

2022-07-29 10:03 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/useEapFormOptions.ts
> +  ), [districtsResponse]);
better naming

2022-07-29 10:03 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/index.tsx
> +          Last Updated: oct 1.2018
Add TODO

2022-08-03 09:05 UTC, barshathakuri commented on src/root/views/Country/Preparedness/EapApplication/EapOverview/index.tsx
> +              </div>
this is needed to style button according to fields

2022-08-03 11:19 UTC, AdityaKhatri requested changes

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EapOverview/index.tsx
> +    };
use random string directly

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EapOverview/index.tsx
> +              ))}
use list

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EapOverview/index.tsx
> +              ))}
use list

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EapOverview/index.tsx
> +            <IoCloudUpload />
```suggestion
          description={strings.eapsFormUploadEapsDocumentsDescription}
        >
          <DREFFileInput
            name="document"
            accept=".pdf"
            error={error?.document}
            fileIdToUrlMap={fileIdToUrlMap}
            onChange={onValueChange}
            setFileIdToUrlMap={setFileIdToUrlMap}
            showStatus
            value={value?.document}
          >
            <IoCloudUpload />
```

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EarlyActions/EarlyActionInput/ActionInput/styles.module.scss
> +
remove empty line

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EarlyActions/EarlyActionInput/IndicatorInput/index.tsx
> +type SetValueArg<T> = T | ((value: T) => T);
move this to utils and use it

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EarlyActions/EarlyActionInput/RisksInput/index.tsx
> +type SetValueArg<T> = T | ((value: T) => T);
use this from utils

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EarlyActions/index.tsx
> +    key: string, datum: EarlyActionValue, index: number
```suggestion
    key: string, 
    datum: EarlyActionValue, 
    index: number,
```

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/EarlyActions/index.tsx
> +  const filteredSectorOptions = sectorOptionMap ? sectorsOptions.filter(n => sectorOptionMap[n.value]) : [];
```suggestion
  const filteredSectorOptions = sectorOptionMap 
    ? sectorsOptions.filter(n => sectorOptionMap[n.value]) 
      : [];
```

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/common.tsx
> +    district_details: DistrictMini[],
```suggestion
    id: number;
    country_details: Country;
    district_details: DistrictMini[];
```

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/EapApplication/index.tsx
> +}
The use of this function might not be needed

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/index.tsx
> +          Last Updated: oct 1.2018
use TextOutput

2022-08-03 11:19 UTC, AdityaKhatri commented on src/root/views/Country/Preparedness/index.tsx
> +            {strings.eapsFormStatus}
use subHeading

2023-06-08 07:37 UTC, closed without merging