Unhide WFP ADAM maps
IFRCGo/go-frontend pull request #2627
Opened 2023-02-03 15:33 UTC by frozenhelium

2023-02-10 11:27 UTC, tnagorra requested changes

2023-02-10 11:27 UTC, tnagorra commented on src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx
> +                          key={hrd.hazard_type}
We don't need this key anymore

2023-02-10 11:27 UTC, tnagorra commented on src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx
> +
```suggestion
```

2023-02-11 08:01 UTC, puranban commented on src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx
> +
done

2023-02-11 08:02 UTC, puranban commented on src/root/views/RegionalRiskWatch/SeasonalRisk/CountryRiskBarChart/index.tsx
> +                          key={hrd.hazard_type}
done removed

2023-02-13 15:04 UTC, tnagorra approved these changes

2023-02-23 09:14 UTC, puranban approved these changes

2023-02-23 09:15 UTC, merged