Add option to use current language in the useRequest
IFRCGo/go-frontend pull request #2722
Opened 2023-04-10 05:33 UTC by frozenhelium

2023-04-20 08:52 UTC, barshathakuri requested changes

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/Page/index.tsx
> +import TranslationWarningBanner from '#components/TranslationWarningBanner';
Please add imports in order

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/SearchSelectInput/styles.module.scss
> +    margin: 0 -1*$spacing;
Please try not to use negative margins

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/ThreeWForm/index.tsx
> +import Container from '#components/Container';
Same as above.

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/ThreeWForm/index.tsx
> +  // const languageMismatch = (isDefined(projectId) && fieldReportResponse?.translation_module_original_language !== currentLanguage) ?? false;
Please remove this

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/ThreeWForm/index.tsx
> +            <Container contentClassName={styles.languageMismatch}>
Please break this container and styling in different line :
<Container 
contentClassName={styles.languageMismatch}
>

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/ThreeWForm/styles.module.scss
> +  .languageMismatch {
Please write languageMismatch in scss format (language-mismatch)

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/ThreeWForm/styles.module.scss
>      color: grey
Please use styling variables

2023-04-20 08:52 UTC, barshathakuri commented on src/root/components/TranslationWarningBanner/index.tsx
> +import styles from './styles.module.scss';
Same as above

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/DrefApplicationForm/index.tsx
> +import Translate from '#components/Translate';
Same as above

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/DrefApplicationForm/styles.module.scss
> +.languageMismatch {
Use scss format

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/DrefOperationalUpdateForm/index.tsx
> +import { languageOptions } from '#utils/lang';
Same as above

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/DrefOperationalUpdateForm/index.tsx
> +                <Container contentClassName={styles.languageMismatch}>
Same as above

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/DrefOperationalUpdateForm/styles.module.scss
> +.languageMismatch {
Same as above

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/FinalReportForm/styles.module.scss
> +  text-align: center;
Same

2023-04-20 08:52 UTC, barshathakuri commented on src/root/views/FlashUpdateApplicationForm/styles.module.scss
> +.languageMismatch {
Same

2023-04-20 10:59 UTC, barshathakuri approved these changes

2023-04-24 04:51 UTC, puranban commented on src/root/components/ThreeWDetails/index.tsx
>                style={{backgroundColor: '#faf9f9', padding: '1.5rem'}}
avoid inline css

2023-04-24 04:54 UTC, puranban commented on src/root/components/ThreeWForm/index.tsx
> +          {languageMismatch && projectDetailsResponse && (
no need to recheck `projectDetailsResponse` value

2023-04-24 06:39 UTC, puranban requested changes
Please do not use auto-formatting.

2023-04-24 06:39 UTC, puranban commented on src/root/components/ThreeWForm/index.tsx
> +
const languageMismatch = isTruthy(projectDetailsResponse?.translation_module_original_language !== currentLanguage);

NOTE: use `isTruthy` from fujs.

2023-04-24 06:39 UTC, puranban commented on src/root/components/TranslationWarningBanner/index.tsx
> +import Translate from '#components/Translate';
Apply the same import rule as requested in the above comment.

2023-04-24 06:39 UTC, puranban commented on src/root/views/DrefApplicationForm/index.tsx
> +
use `isTruthy` here too.

2023-04-24 06:39 UTC, puranban commented on src/root/views/FieldReportForm/index.tsx
> +  }, [submitRequest, userDetails, currentStep, setCurrentStep, validate, onErrorSet, countryIsoOptions, disasterTypeOptions, eventOptions, strings.fieldReportCOVID19, value.country, value.event, repo
use linebreak when there are more than three dependencies.

2023-06-29 05:10 UTC, frozenhelium commented
@szabozoltan69 lets merge and deploy this after https://github.com/IFRCGo/go-api/pull/1834

2023-06-29 09:54 UTC, szabozoltan69 commented
@frozenhelium I'll do the merges  (both api and frontend), despite of the fact that locally I could not use these new translation branches. The frontend gave some kind of CORS error.

2023-06-29 09:57 UTC, merged

2023-06-29 10:11 UTC, szabozoltan69 commented
@frozenhelium @thenav56 Do we have to set some env variable for the frontend change of translations?

2023-06-29 11:03 UTC, szabozoltan69 commented
@frozenhelium @thenav56 Both backend and frontend are deployed to Staging.