Add buttons for the new ui elements
IFRCGo/go-frontend pull request #2743
Opened 2023-04-26 11:33 UTC by priyesh777

- Add different types of button as a part of UI elements

2023-05-03 05:01 UTC, samshara commented on src/root/views/GoUI/styles.module.scss
> +  --go-ui-border-radius-full: 9999px;
Let's put the comments to side of the variables as before.

2023-05-03 05:01 UTC, samshara commented on src/root/views/GoUI/styles.module.scss
> +  --go-ui-color-background: #F7F7F7;
Let's remove this definition as it is already defined in line 156.

2023-05-03 05:48 UTC, priyesh777 commented on src/root/views/GoUI/hooks/index.tsx
This file will be used for drop-down after this branch will be merged.

2023-05-03 08:37 UTC, shreeyash07 requested changes

2023-05-03 11:44 UTC, shreeyash07 approved these changes

2023-05-04 04:27 UTC, samshara commented on src/root/components/Heading/index.tsx
Remove this unused component

2023-05-04 04:27 UTC, samshara commented on src/root/views/GoUI/hooks/index.tsx
Let's remove this.

2023-05-04 04:52 UTC, samshara approved these changes

2023-05-04 04:52 UTC, samshara commented on src/root/components/Heading/index.tsx
Let's remove this.

2023-05-04 04:52 UTC, samshara approved these changes

2023-05-04 04:52 UTC, merged