Add numberInput component for number specific inputs
IFRCGo/go-frontend pull request #2772
Opened 2023-05-10 10:23 UTC by priyesh777

## changes:
- Add NumberInput that is used for inputs focused on taking numbers

## Addresses:
- Task (NumberInput): https://github.com/toggle-corp/ifrc-go-meta/issues/127#issue-1701328448

2023-05-10 11:03 UTC, samshara commented on src/root/views/GoUI/examples/NumberInputExample/index.tsx
use 2 spaces for indentation.

2023-05-11 04:37 UTC, shreeyash07 requested changes
Please format all files in 2 spaces indication

2023-05-12 04:23 UTC, shreeyash07 approved these changes

2023-05-12 04:25 UTC, samshara approved these changes

2023-05-12 04:25 UTC, merged